language: rust
jobs:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      osx_image: xcode11.4 # Catalina
      rust: stable
      env: TARGET=x86_64-apple-darwin

env:
  global:
    # Default target on travis-ci.
    - HOST=x86_64-unknown-linux-gnu
    # Used on the deployment script
    - PROJECT_NAME=lowcharts

before_deploy:
  - bash ci/before_deploy

deploy:
  provider: releases
  api_key:
    secure: "ERwRPSWDU9cBE5DysvxPBlTz+BYVUjk+NpZZW1MWgd1MLj2HyW618QyJ025F57GaOed8kVvPXaSJ6wnsOhSnz5r3zI4kZueN5AwC6slAnmLqro6/5QBmCtKaK1Di72xJoF1iMh78jRVmIt+NuMo3crduZke+1JRcWnOe/qasDCfiRxfAJwRc4rj3Y0bfPLC1AVOasD4sUmaafwJAOjyuBJW7x7vu1fQTHs/QEThnoqdHJSTR8htd77ff7Iv+3+kFWYALOA2S8A8CGpEvHEAs6Yvt0ndaBqI/wfG6GUPZYErzJc2ZsVqjvWQexVw+J8pW54uOaDNfg6UTOMPTBdZC+Nz3VkIZehEHcNDjPCkp3am4DKubmhZz2XK8FvY5fNIRR+7dKb61USvzS9dv8INYrwjqFUOGqgS2TzzaqDELXsKyN+mMrr1VWc6RfnBnt1v9GH6KBwySYZbAwDaGapFOmYdj9/bg7wfD+7xk2cmq+8R4vukpEIHcQs8dNusYltQ/btYL0uTGToCQnjB3djSY30DUa+dvpgRzhL0Mw4CsXEjdOVCRP8sJpx/lUeRZv4ZKjYTKv96WBBxTlbNV55R9PPcr4d5uTqu+iSg0vDnDejyuRyPi9klj6bpiFumjLNqSNnJA7nQq7RWE9f8Xew7VEmNJd5MmJfS7KQiT8B0LGkw="
  file:
    - $PROJECT_NAME-$TRAVIS_TAG-$TARGET.tar.gz
  skip_cleanup: true
  on:
    tags: true

install:
  # prevent target re-add error from rustup
  - if [[ $TRAVIS_OS_NAME = linux && $HOST != $TARGET ]]; then rustup target add $TARGET; fi

notifications:
  email:
    on_success: never
