[package]
name = "lowcharts"
version = "0.1.0"
authors = ["JuanLeon Lahoz <juanleon.lahoz@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
yansi = "0.5.0"
isatty = "0.1"
derive_builder = "0.10.0"
regex = "1.4.5"

[dev-dependencies]
float_eq = "0.5.0"
tempfile = "3"
